version: "3"
services:
  backend:
    build: ./apps/account_manager
    image: account_manager
    environment:
      - DATABASE_PASSWORD=development
      - REDIS_URL=redis://0.0.0.0:6379/0/cache
      - DATABASE_HOST=mysql
    links:
      - mysql
      - redis
    ports:
      - 3000:3000
    command: bundle exec rails s
  frontend:
    build: ./apps/account-frontend
    image: account_frontend
    links:
      - backend
    ports:
      - 4200:4200
  mysql:
    image: mysql:5.6.36
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=development
  redis:
    image: redis:3.2.11
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis:/var/lib/redis/data
